### ISSUE TITLE
Log in failed

### ISSUE THREAD

**Issue by anton** [AHJenin/uva-tool#2]
```
$ uva-tool -login
Input username: username
Input password: password
Remember? [y/n] y
Log in failed

```

**Comment by anton** [comment]
https://github.com/arafat-hasan/uva-tool/blob/master/src/uva-tool.cpp#L333

Solution: Change uva.onlinejudge.org to onlinejudge.org.

**Comment by arafat-hasan** [comment]
Very sorry for the late reply. I just noticed after your pull request today, did not notice before.

Some issue has been raised for lack of maintenance and my remissness. I was planning to fix them for many days, but could not make time. Hopefully, I will be able to fix them soon.

Your work has been great!

**Comment by anton** [comment]
Thanks!

I should inform you that I've not looked at the url for uhunt.onlinejudge.org. I think it's worth to take a look at that and verify that hunt-feature still works in uva-tool.

**Comment by arafat-hasan** [comment]
Yes, the Hunt feature is not working, your concern is definite. I think, there are some problems, possibly other than URL. I will take care of it, asap.
